require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcrypt');
const User = require('../src/models/user.model');
const FinancialRecord = require('../src/models/record.model');

const connectDB = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('MongoDB connected for seeding');
    } catch (error) {
        console.error('MongoDB connection error:', error);
        process.exit(1);
    }
};

const seedDatabase = async () => {
    await connectDB();

    try {
        console.log('Seeding users...');
        const usersToSeed = [
            {
                name: 'Admin User',
                email: 'admin@finance.dev',
                password: 'Admin@1234',
                role: 'ADMIN'
            },
            {
                name: 'Analyst User',
                email: 'analyst@finance.dev',
                password: 'Analyst@1234',
                role: 'ANALYST'
            },
            {
                name: 'Viewer User',
                email: 'viewer@finance.dev',
                password: 'Viewer@1234',
                role: 'VIEWER'
            }
        ];

        const insertedUsers = {};

        for (const userData of usersToSeed) {
            let user = await User.findOne({ email: userData.email });
            if (!user) {
                const hashedPassword = await bcrypt.hash(userData.password, 10);
                user = await User.create({
                    ...userData,
                    password: hashedPassword
                });
                console.log(`Created user: ${user.email}`);
            } else {
                console.log(`User already exists: ${user.email}`);
            }
            insertedUsers[userData.role] = user;
        }

        console.log('Seeding financial records...');
        
        // We will assert idempotency by checking if total records >= 20.
        // If not, we insert. If we want to be strictly idempotent on multiple runs
        // we can check if records already exist. Since records don't have a unique identifier
        // other than _id and exact natural keys, we check count.
        const recordCount = await FinancialRecord.countDocuments();
        
        if (recordCount === 0) {
            const adminUser = insertedUsers['ADMIN'];
            const categories = ['Salary', 'Freelance', 'Rent', 'Food', 'Utilities', 'Entertainment'];
            const types = ['INCOME', 'EXPENSE'];
            
            const records = [];
            const now = new Date();

            for (let i = 0; i < 25; i++) {
                const isIncome = i % 3 === 0; // Roughly 1/3 income, 2/3 expense
                const type = isIncome ? 'INCOME' : 'EXPENSE';
                const category = isIncome ? categories[i % 2] : categories[2 + (i % 4)];
                
                const date = new Date(now);
                date.setDate(date.getDate() - (i * 7)); // Spread over past ~6 months

                records.push({
                    amount: Math.round(((Math.random() * 500) + 50) * 100) / 100, // random amount 50-550
                    type,
                    category,
                    date,
                    notes: `Autogenerated note ${i}`,
                    createdBy: adminUser._id
                });
            }
            
            await FinancialRecord.insertMany(records);
            console.log(`Inserted 25 financial records.`);
        } else {
            console.log(`Database already has ${recordCount} records. Skipping record seeding.`);
        }

        console.log('Database seeding completed successfully.');
    } catch (error) {
        console.error('Error seeding database:', error);
        process.exitCode = 1;
    } finally {
        await mongoose.disconnect();
        console.log('MongoDB disconnected after seeding');
    }
};

seedDatabase();
